/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const RouteLocation: typeof import('vue-router/auto')['RouteLocation']
  const RouteLocationNormalized: typeof import('vue-router/auto')['RouteLocationNormalized']
  const RouteLocationNormalizedLoaded: typeof import('vue-router/auto')['RouteLocationNormalizedLoaded']
  const RouteLocationRaw: typeof import('vue-router/auto')['RouteLocationRaw']
  const RouteParams: typeof import('vue-router/auto')['RouteParams']
  const RouteParamsRaw: typeof import('vue-router/auto')['RouteParamsRaw']
  const RouterLink: typeof import('vue-router/auto')['RouterLink']
  const defineLoader: typeof import('vue-router/auto')['defineLoader']
  const definePage: typeof import('unplugin-vue-router/runtime')['_definePage']
  const onBeforeRouteLeave: typeof import('vue-router/auto')['onBeforeRouteLeave']
  const onBeforeRouteUpdate: typeof import('vue-router/auto')['onBeforeRouteUpdate']
  const useLink: typeof import('vue-router/auto')['useLink']
  const useRoute: typeof import('vue-router/auto')['useRoute']
  const useRouter: typeof import('vue-router/auto')['useRouter']
}
